### ISSUE TITLE
'https://github.com/fastogt/common.git/' not found

### ISSUE THREAD

**Issue by yakirChen** [fastogt/fastonosql#49]
```shell
ninja: build stopped: subcommand failed.
Command ['ninja', 'install'] finished successfully
Cloning into 'common'...
remote: Repository not found.
fatal: repository 'https://github.com/fastogt/common.git/' not found
Traceback (most recent call last):
  File "build_env.py", line 366, in <module>
    request.build(args_bs, args_prefix_path)
  File "build_env.py", line 325, in build
    self.build_common(cmake_line, make_install)
  File "build_env.py", line 89, in build_common
    raise ex
  File "build_env.py", line 74, in build_common
    cloned_dir = utils.git_clone('https://github.com/fastogt/common.git', abs_dir_path)
```

**Comment by topilski** [comment]
Hi @yakirChen thank you for the issuie, but i want to know why you don't want to subscribe?

**Comment by topilski** [comment]
You don't wan't to answer why should i give you access to the private library, right?

**Comment by yakirChen** [comment]
Thanks for your answer . 
Now I have `Redis Cli` . Thanks

**Comment by topilski** [comment]
Good choose, thank you!

**Comment by topilski** [comment]
Hi @yakirChen , we opened downloads on site, not needed to build.

**Comment by yakirChen** [comment]
@topilski  **Thank you very much .**

**Comment by topilski** [comment]
@yakirChen you are welcome, we need your feedback, and we open for our users. sorry for this.
