### ISSUE TITLE
build_env calls to utils.git_clone use git@github.com urls instead of https urls which fails for non-logged in users

### ISSUE THREAD

**Issue by syserr0r** [fastogt/fastonosql#75]
These fail on msys2 with the following stacktrace (first line is a print I added to all subprocess calls to help debugging):
```
Attempting to execute: ['git', 'clone', '--depth=1', 'git@github.com:fastogt/qscintilla.git', 'qscintilla']
Cloning into 'qscintilla'...
error: cannot run C:\Program Files\PuTTY\plink.exe: No such file or directory
fatal: unable to fork
Traceback (most recent call last):
  File "build_env.py", line 306, in <module>
    request.build_qscintilla()
  File "build_env.py", line 76, in build_qscintilla
    cloned_dir = utils.git_clone('git@github.com:fastogt/qscintilla.git')
  File "C:\msys32\mingw64\lib\python3.7\site-packages\pyfastogt-1.1.0-py3.7.egg\pyfastogt\utils.py", line 142, in git_clone
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'qscintilla'
```

Instead I replaced all references to `git@github.com:fastogt` with `https://github.com/fastogt/` and stripped the trailing `.git`

**Comment by topilski** [comment]
This not failed on our build machines.

**Comment by syserr0r** [comment]
It wouldn't as I presume your build machines have ssh for git set-up.

For users wishing to build who have not got git ssh set-up this will fail.

Alternatively this could be documented in the build instructions?

**Comment by topilski** [comment]
In wiki page.
