### ISSUE TITLE
Problem compile on Win Server 2016 and Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by kroxiksut** [fastogt/fastonosql#92]
Hello! 
On win Server 2016 I'm install latest install msys2 http://msys2.github.io/ and all packeges from list.
When execute python3 build_env.py I get error on openSSL library
```
Downloading: openssl-1.1.1b.tar.gz Bytes: 8213737
Extracting: C:/Users/▒▒▒▒▒▒▒▒▒▒▒▒▒.WIN-9APTP0E822J/fastonosql/build/build_windows_env/openssl-1.1.1b.tar.gz
Traceback (most recent call last):
  File "C:\Users\▒▒▒▒▒▒▒▒▒▒▒▒▒.WIN-9APTP0E822J\fastonosql\build\build_env.py", line 280, in <module>
    request.build_openssl(openssl_default_version)  #
  File "C:/msys64/mingw64/lib/python3.10/site-packages/pyfastogt-1.2.2-py3.10.egg/pyfastogt/build_utils.py", line 232, in build_openssl
  File "C:/msys64/mingw64/lib/python3.10/site-packages/pyfastogt-1.2.2-py3.10.egg/pyfastogt/build_utils.py", line 83, in build_command_configure
  File "C:/msys64/mingw64/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:/msys64/mingw64/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:/msys64/mingw64/lib/python3.10/subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 ▒▒ ▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒▒▒▒▒▒ Win32
```
I'm test build on ubuntu 20.04 LTS. And build_env script request login/password from github. My username with password - not correct.
```
-- Up-to-date: /usr/local/lib/cmake/leveldb/leveldbConfigVersion.cmake
Cloning into 'fastonosql_core'...
Username for 'https://github.com': 
```
UPD: if execute on widows with flags **python3 build_env.py  --without-openssl --without-fastonosql-core** and linux with flag **python3 build_env.py --without-fastonosql-core**, then when execute **python3 build.py ..** I'm get error 

```
20.0% Build project
ninja: error: loading 'build.ninja': ▒▒ ▒▒▒▒▒▒▒ ▒▒▒▒▒ ▒▒▒▒▒▒▒▒▒ ▒▒▒▒.

80.0% Trying to get package file name
Traceback (most recent call last):
  File "C:\Users\▒▒▒▒▒▒▒▒▒▒▒▒▒.WIN-9APTP0E822J\fastonosql\build\build.py", line 278, in <module>
    request.build(cmake_root, branding_options, 'build_' + platform_str, build_system, packages, saver)
  File "C:\Users\▒▒▒▒▒▒▒▒▒▒▒▒▒.WIN-9APTP0E822J\fastonosql\build\build.py", line 176, in build
    in_file = open('CPackConfig.cmake', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'CPackConfig.cmake'

```

Please help me

**Comment by topilski** [comment]
Not intrested

**Comment by Pearo** [comment]
For those who still looking for answers to this:  windows cannot execute scripts natively, so you need to tell it how to. For MSYS2, change build_env.py to 
`compile_cmd = ["bash", executable, "--prefix={0}".format(abs_prefix_path)]`

I have other changes to python code, but you may need to add` 'shell = True'` as argument too

@topilski  The only reason I make this work is because I want to trial it for more than one day, then my customer (a large enterprise) will probably buy it if its any good.

EDIT. Pointless. looks like old mate has locked down part of the build so you cant build yourself. https://github.com/fastogt/fastonosql_core/
